version: '3.8'

services:
  db:
    image: postgres:16
    container_name: banking-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    expose:
      - "8080:8080"
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
      KAFKA_CONNECTION: ${KAFKA_CONNECTION}
    command: ["./wait-for-it.sh", "db", "5432", "--", "java", "-jar", "banking.jar"]
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh

  nginx:
    image: nginx:stable-alpine
    container_name: banking-nginx
    depends_on:
      - app
    ports:
      - "8081:80"    # HTTP access
      - "8443:443"   # HTTPS access
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      # Use the default Kafka data directory
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_LOG_RETENTION_HOURS: 168  # 7 days retention
      KAFKA_LOG_RETENTION_BYTES: -1   # No size limit
    volumes:
      - kafka_data:/kafka/kafka-logs
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
    external: false
  kafka_data:
    external: false
  zookeeper_data:
    external: false
  zookeeper_log:
    external: false