version: '3.8'

services:
  db:
    image: postgres:16
    container_name: banking-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    expose:
      - "8080:8080"
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
    command: ["./wait-for-it.sh", "db", "5432", "--", "java", "-jar", "banking.jar"]
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
  nginx:
    image: nginx:stable-alpine
    container_name: banking-nginx
    depends_on:
      - app
    ports:
      - "8081:80"    # HTTP access
      - "8443:443"   # HTTPS access
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

volumes:
  postgres_data: