version: '3.8'

services:
  db:
    image: postgres:16
    container_name: banking-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-app
    depends_on:
      - db
    expose:
      - "8080:8080"
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command: ["java", "-jar", "banking.jar"]

  nginx:
    image: nginx:stable-alpine
    container_name: banking-nginx
    depends_on:
      - app
    ports:
      - "8081:80"    # HTTP access
      - "8443:443"   # HTTPS access
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

volumes:
  postgres_data: