spring:
  profiles:
    active: dev

logging:
  level:
    liquibase: INFO       # or DEBUG for more detail
    liquibase.executor.jvm: DEBUG
    liquibase.changelog: DEBUG
    liquibase.database: DEBUG
    liquibase.lockservice: DEBUG
    liquibase.parser: DEBUG

